# Generated by Django 2.0.2 on 2019-06-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190621_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
